on: 
  workflow_dispatch:
jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: add platform_secrets 
      env:
          PLATFORM_SECRETS: ${{ secrets.PLATFORM_SECRETS }}
      run: pwd;ls;echo $PLATFORM_SECRETS >  herow-sdk-ios/connection/platform-secrets.plist;cd  herow-sdk-ios/connexion;ls
    - name: Start build
      run: | 
          rm -rf output
          xcodebuild -workspace herow_sdk_ios.xcworkspace -scheme build -destination "platform=iOS Simulator,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - name: Deploy
      run: |
         SDK_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" herow-sdk-ios/Info.plist)
         echo $SDK_VERSION
         pwd; cd output; ls
          - name: Pushes test file
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
          source-directory: '$SDK_VERSION'
          destination-github-username: 'herow'
          destination-repository-name: 'test'
          user-email: carles3@pina.cat
