name: Build and Test

on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: add platform_secrets 
      env:
          PLATFORM_SECRETS: ${{ secrets.PLATFORM_SECRETS }}
      run: pwd;ls;echo $PLATFORM_SECRETS >  herow-sdk-ios/Connection/platform-secrets.plist;cd  herow-sdk-ios/Connection;ls
    - name: Start xcodebuild test
      run: |
          xcodebuild clean test -workspace herow_sdk_ios.xcworkspace -scheme herow_sdk_ios -destination "platform=iOS Simulator,name=iPhone 11 Pro"

