name: CI

on: 
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@develop
    - name: add platform_secrets 
      env:
          PLATFORM_SECRETS: ${{ secrets.PLATFORM_SECRETS }}
      run: cd herow-sdk-ios/connexion ;echo $PLATFORM_SECRETS > platform-secrets.plist
    - name: Start xcodebuild test
      run: |
          xcodebuild clean test -workspace herow-sdk-ios.workspace -scheme herow-sdk-ios -destination "platform=iOS Simulator,name=iPhone 11 Pro"
